apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  labels: 
    app: wordpress
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi
