apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:5.7
        name: wordpress
        env: 
        - name: WORDPRESS_DB_HOST
          value: mydb
        ports: 
        - containerPort: 80
          name: wordpress
        volumeMounts:
          - name: wp-persistent-st
            mountPath: /var/www/html
      volumes:
      - name: wp-persistent-st
        persistentVolumeClaim:
          claimName: wp-pvc

      
